### ISSUE TITLE
Matrix printing locking up the REPL

### ISSUE THREAD

**Issue by mortenpi** [soumitradev/TermLayouts.jl#3]
So we know that trying to evaluate even something like `[1 2; 3 4]` locks up the REPL.

I littered the code with some debug logging into a file (https://github.com/mortenpi/TermLayouts.jl/commit/84569dc25ff4a363ccd154f7a73199bdd6bad215) and I think I partially figured out why printing matrices crashes -- it seems like `parseANSI` throws, which kills the REPL reading loop. This is what I see in the log:

```
DEBUG[TermLayouts.jl:129]: render
DEBUG[TermLayouts.jl:189]: main: control_value=
DEBUG[TermLayouts.jl:113]: read...
DEBUG[TermLayouts.jl:115]: read: > 
[0K[32mjulia> [0m
[7C[1 2; 3 4]
[17C

DEBUG[TermLayouts.jl:120]: read: parseANSI
DEBUG[TermLayouts.jl:185]: main: enter
DEBUG[TermLayouts.jl:113]: read...
DEBUG[TermLayouts.jl:115]: read: > [?2004l[0m2×2 Matrix{Int64}:
 1  2
 3  4


[0K
[0K[32mjulia> [0m
[7C
[7C[?2004h
[0K[32mjulia> [0m
[7C
[7C
DEBUG[TermLayouts.jl:122]: read: parseANSI throws: StringIndexError("\e[?2004l\e[0m2×2 Matrix{Int64}:\n 1  2\n 3  4\n\n\r\e[0K\r\e[0K\e[32mjulia> \e[0m\r\e[7C\r\e[7C\e[?2004h\r\e[0K\e[32mjulia> \e[0m\r\e[7C\r\e[7C", 15)
DEBUG[TermLayouts.jl:129]: render
DEBUG[TermLayouts.jl:189]: main: control_value=EXIT
DEBUG[TermLayouts.jl:200]: main: end
```

**Comment by soumitradev** [comment]
From basic testing, looks like a Unicode Issue. The `×` character seems to be 2 bytes, which is what is causing the index to go out of range, since Unicode indexing renders some indices invalid: https://docs.julialang.org/en/v1/manual/strings/#Unicode-and-UTF-8
